### ISSUE TITLE
brazilian portuguese typo - word cinqüenta

### ISSUE THREAD

**Issue by helder1983** [kwn/number-to-words#101]
Hi.

just a little issue. in brazilian portuguese the character ü in word cinqüenta is not used anymore. now it's just the character 'u'
please, change cinqüenta to cinq**u**enta in file \src\Legacy\Numbers\Words\Locale\Pt\BR.php

Thanks!

**Comment by kwn** [comment]
Hi @helder1983 

Thank you for reporting an issue. Could you please open a pull request and update necessary tests? Your help would be really appreciated.

**Comment by lucasbeckps** [comment]
Hi @kwn!

I recently opened #110 for this fix

**Comment by kwn** [comment]
Thank you. I merged the PR. Just released it in `1.12.2`
