### ISSUE TITLE
Is there a way to push new currencies like INR etc?

### ISSUE THREAD

**Issue by sanmayad** [kwn/number-to-words#105]
I am struggling with using the same for INR currency.
I am searching for a way to set currencyNames to 'INR' => [['Rupees'], ['paisa']],

**Comment by kwn** [comment]
Hi @sanmayad 

For which language?

**Comment by sanmayad** [comment]
@kwn english

**Comment by kwn** [comment]
Yes, you can add it in the English dictionary:

https://github.com/kwn/number-to-words/blob/master/src/Language/English/EnglishDictionary.php#L43

While opening pull request please add some unit tests.
