### ISSUE TITLE
Currencies subunits/fraction

### ISSUE THREAD

**Issue by ArturTG** [kwn/number-to-words#12]
cast "(float) $value" from Number model cuts currency fraction for example:

->toWords(50.99) // works correctly

->toWords(50.90) //does not works correctly cuts currency to 50.9 and displays pięćdziesiąt złotych dziewięć groszy

**Comment by kwn** [comment]
Thanks for reporting. This is not a case anymore since `toWords()` in currency transformer accepts integers (you need to pass 5090 instead of 50.90).
