### ISSUE TITLE
Implementing an autoloader for usage without docker

### ISSUE THREAD

**Issue by BeppeMarnell** [kwn/number-to-words#134]
Hi everyone, thanks for the work that you all have put in this library. I am not using docker and when I start calling the method to get the transformer I get a cascade of error. I was wondering whether you could implement an autoloader or if there is a quick way to solve all these "Class not found" errors.

I tried implementing an autoloader but with poor results (I am not an expert in php).

Thank you for your time.

**Comment by BeppeMarnell** [comment]
I understand compose is the way, but in my case I cannot use it. Thank you.

**Comment by kwn** [comment]
Just out of curiosity - what stops you from using composer?
