### ISSUE TITLE
Documentation - namespace

### ISSUE THREAD

**Issue by ColmMcBarron** [kwn/number-to-words#14]
The documentation is slightly incorrect, you need to instciate it with the namespace:

`$numberToWords = new NumberToWords();`

It should be:

`$numberToWords = new NumberToWords\NumberToWords();`

**Comment by kwn** [comment]
Hi there. Thanks for reporting the issue. You can create an instance with fully qualified name or simply import the class using `use` statement. I've updated docs to accordingly and I've bumped a version to 1.1.1.
