### ISSUE TITLE
Spelling of negative numbers in German: "Minussomething" vs "minus something"

### ISSUE THREAD

**Issue by rotdrop** [kwn/number-to-words#170]
Many thanks for this nice piece of code!

However: I am pretty sure that in German the minus is spelled out separated by a space and in lowercase. But of course: being a German I still may be wrong though the stock PHP NumberFormatter also handles it that way. So it probably should be:
`minus fünfzehn` instead of the `Minusfünfzehn` (i.e. spelled out -15 in German).

**Comment by kwn** [comment]
Hey @rotdrop. Thanks for reporting the issue. It been fixed in https://github.com/kwn/number-to-words/pull/172 and released in 2.9.1

**Comment by rotdrop** [comment]
Thank you!
