### ISSUE TITLE
fr_FR is missing

### ISSUE THREAD

**Issue by MisterDuval** [kwn/number-to-words#174]
you could use this https://github.com/juliendb/NumberToString/blob/master/NumberToString.php as a start for dictionary

**Comment by Bryce-Colton** [comment]
In fact french language is already working in this library : 

![image](https://github.com/kwn/number-to-words/assets/142520814/fbbbd851-5794-49fc-bfc6-d361a36d5b0e)


Maybe it would be more clear if an alias fr_FR for fr exists.

@kwn : what about add an alias fr_FR for "fr" identifier ?

**Comment by MisterDuval** [comment]
I can't see the dictionnary, I only saw the Belgian one.

**Comment by Bryce-Colton** [comment]
It is here : src/Legacy/Numbers/Words/Locale/Fr.php

**Comment by Bryce-Colton** [comment]
@kwn : Any thoughts on this topic ?

**Comment by kwn** [comment]
Hi @Bryce-Colton 

The support has been added in 2.11.0. Thanks!
