### ISSUE TITLE
Enhancement: Automatically Set Default Currency Based on Locale

### ISSUE THREAD

**Issue by ngekoding** [kwn/number-to-words#178]
**Problem**

Currently, we need to manually define a currency identifier even when a specific locale is already set. This seems redundant and could lead to potential errors or inconsistencies.

**Proposal**

Could we simplify this process by using the default currency associated with the specified locale? For instance, when the locale is set to Indonesian (`id`), the default currency should automatically be Indonesian Rupiah (`IDR`).

Thank you for considering this enhancement!

**Comment by kwn** [comment]
I see a very little value in having implicit currency based on the locale, as it only applies for the languages that are used in one country.

What would be the default currency for English language? Should it be US Dollar, British Pound or Australian Dollar? For German language - Euro or Swiss Frank? For Spanish - Euro, Mexican Peso or Argentinian Peso?

I think having a default currency introduces more confusion in that case.

**Comment by kwn** [comment]
Closing as not planned for implementation.
