### ISSUE TITLE
To words method missing

### ISSUE THREAD

**Issue by emodatt08** [kwn/number-to-words#23]
Hi, I looked into your package and realized the "toWords()" method was missing, Kindly assist!!

**Comment by kwn** [comment]
Hi @emodatt08. Could you elaborate it a bit more? Every transformer has `toWords()` method. E.g. [EnglishNumberTransformer.php#15](https://github.com/kwn/number-to-words/blob/master/src/NumberTransformer/EnglishNumberTransformer.php)
