### ISSUE TITLE
Optimal usage

### ISSUE THREAD

**Issue by janhartigan** [kwn/number-to-words#3]
So in #2 we briefly talked about how someone might use this library. Let's talk first about how to use it now. An example:

```php
//build the registry of transformers we want to work with
$registry = new TransformerFactoriesRegistry([
    new EnglishTransformerFactory
]);

//create the number to words "manager" class
$numberToWords = new NumberToWords($registry);

//build a new currency transformer
$currencyTransformer = $numberToWords->getCurrencyTransformer('en', 'USD', SubunitFormat::Words);

//build an Amount that we can pass to the transformer
$amount = new Amount(new Number(50), new Currency('USD'), new SubunitFormat(SubunitFormat::Words));

//do the conversion
$currencyTransformer->toWords($amount); //outputs "fifty dollars and zero cents"
```

So as a first point, I think we should decide where the currency and subunit format information should live. In the above code, this line:

```php
$numberToWords->getCurrencyTransformer('en', 'USD', SubunitFormat::Words);
```

Is a bit deceptive because it's not actually creating an English, US Dollar, subunit word transformer. It's creating an English transformer that can convert any `Amount` into words. The `Amount` has meta information about its currency and subunit format. I think what's obvious is that the subunit format shouldn't be a part of the `Amount` because it doesn't really describe the amount, but the transformation that needs to occur. A similar argument could be made for the currency...it's simple a facet of how you convert a particular number into words.

So if we split these concepts off into the transformer creation, we can simplify the data structures a bit:

```php
//this now uses the second and third parameters to instruct the transformer creation
$currencyTransformer = $numberToWords->getCurrencyTransformer('en', 'USD', SubunitFormat::Words);

//do the conversion
$currencyTransformer->toWords(new Number(50)); //outputs "fifty dollars and zero cents"
```

The one downside of this is that it puts a bit more work up to the service registration layer (i.e. you need to explicitly create an English, USD, subunit word transformer instead of having a more flexible transformer that can be used in a bunch of different ways). However, I think a decently-architected system won't have to worry about this as the transformer dependency needs to be explicitly created anyway.

So then maybe we can do one better by eliminating the `Number`:

```php
$currencyTransformer->toWords(50); //outputs "fifty dollars and zero cents"
$currencyTransformer->toWords(49.99); //outputs "forty nine dollars and ninety nine cents"
```

We could still convert that int/float to a `Number` in the transformer, of course.

Let me know what you think..

**Comment by kwn** [comment]
@janhartigan 
Yes, I totally agree. I don't remember why I've introduced value objects for numbers, amounts etc. Probably I wanted to introduce some strictness around passing arguments to transformers. My original idea was to create an extendible library with bunch of different transformers (simple number, money amount, angle etc). Probably I wanted to implement some basic logic, like simple validation.

Second thing I wanted to implement is a Twig (+other templating systems) extension, which allows to convert a number on the fly. Something like:

```
<p>You have to pay {{ invoice.total_inc_vat|currency_to_words('en', invoice.currency) }}</p>
```

I was afraid I won't be able to implement desired behaviour with your suggestion, but I think I'll just have to change a behaviour of Twig extension. 

I agree it's better to create a couple of services explicitly. I'm worried that during integration someone will have to create a bit too many services (no of languages * no of currencies), but the truth is, that in real world in most cases services offer one language with one currency.

I'll have a look at this a bit closer during the week. Thanks!

**Comment by kwn** [comment]
Refactored in https://github.com/kwn/number-to-words/pull/4 :+1:
