### ISSUE TITLE
Add Breton language

### ISSUE THREAD

**Issue by Wanibzh29** [kwn/number-to-words#45]
Hello,
How are you,
Will it be possible to add Breton language to this project?

Regards
Pierre

**Comment by kwn** [comment]
Hi @Wanibzh29 

I'm fine, thanks. Feel free to contribute and add a Breton language if you need it.

Thanks!

**Comment by Wanibzh29** [comment]
Hi @kwn,
Glad to see you're fine! :)
I have created a few months ago a repository,
there is in it the basic corpus to set up the converter, I think.
It is possible to access to it by following this link below:
https://github.com/Wanibzh29/09.-Breton-numbers.

Unfortunately my coding capacities are really limited... :/
So which are the first files you will advise me to work on them firstly?
I'll try to work on it.
If it is too difficult for me I will ask you back for some help.
Does it suit you?
Best
Pierre

**Comment by kwn** [comment]
I'm closing the issue for now. Please create a pull request once you create an implementation. Thank you.
