### ISSUE TITLE
UAH not cent

### ISSUE THREAD

**Issue by dejurin** [kwn/number-to-words#46]
`'UAH' => [
            [2, 'гривна', 'гривны', 'гривен'],
            [1, 'цент', 'цента', 'центов']`
**1 UAH = 100 копеек**, is called as well as a Russian kopeyka
`You should change [ 'цент', 'цента', 'центов']  to [ 'копейка', 'копейки', 'копеек']`

**Comment by kwn** [comment]
Thank you for reporting the issue. Could you please open a pull request and fix it?

**Comment by dejurin** [comment]
yes, sure

**Comment by mazhurnyy** [comment]
Ua.php  'гривня'    and not  'гривна'
'UAH' => [ [2, 'гривня', 'гривні', 'гривень'], [1, 'копійка', 'копійки', 'копійок'], ],

**Comment by wbrframe** [comment]
Fixed and added options for transformers:
https://github.com/kwn/number-to-words/pull/55

**Comment by kwn** [comment]
Thank you @wbrframe 🥇

**Comment by kwn** [comment]
@dejurin Fix released in `1.6.1` version.
