### ISSUE TITLE
Romanian number correction

### ISSUE THREAD

**Issue by kassayAkos** [kwn/number-to-words#71]
The numer 14 is in an informal form.
correct form : patrusprezece

https://github.com/kwn/number-to-words/blob/c93b5d5c7a1fdf446c99bcc70dbc86e2334ccebb/src/Language/Romanian/Dictionary.php#L49

**Comment by ethmelly** [comment]
Nobody is using 'patrusprezece' although indeed a correct form also.
The correct form is still 'paisprezece' and commonly adopted and used.
"Paisprezece" is formal , don't mistake it for the form "paispe".

https://dexonline.ro/definitie/paisprezece

**Comment by ethmelly** [comment]
By the same logic for the number 16 :
'saisprezece' is correct and not "sasesprezece"

**Comment by kassayAkos** [comment]
We are using this library for generating receipts where the final number has to be written by letters too. According to our accountant the `patrusprezece` is the accepted and used version on receipts. 

You are indeed right, in everyday language the "paisprezece" and "paispe" are commonly used. 
In the case of 16 the `saisprezece ` is used.

We would appreciate if you could change it.

**Comment by ethmelly** [comment]
I'm not the owner of this repo , @kwn is.

If you need to use "patrusprezece" i would suggest just creating your own class extending original Romanian/Dictionary.php and change the form in order to use that one.

I suggest that you ask for another opinion since i know that "patrusprezce" is the archaic form and "paisprezece" is the literal form , but i could be wrong.

Either way feel free to make a pull request and @kwn will decide to merge it or not.

**Comment by kwn** [comment]
Hi @kassayAkos and @ethmelly. Thank you for raising an issue. I just spoke with my Romanian friend and he said that we should be using `paisprezece` (so as it is right now) - similarly to the number 16. He also showed me this article:

https://destepti.ro/cum-este-corect-patrusprezecepaispepaisprezece-sasesprezecesaispesaisprezece-optisprezeceoptaspeoptsprezece-noosprezecenouasprezece

I don't know Romanian, so I'm going to follow the recommendation of my trusted friend. I'm going to close the issue.

**Comment by kassayAkos** [comment]
@kwn Thank you for taking the time to took into it. In the end we went with `paisprezece`, and till our users won't complain about it we wont change it.

Thanks again, and keep up the good work!
