### ISSUE TITLE
[ru] Incorrect sextillion tests

### ISSUE THREAD

**Issue by andrey-helldar** [kwn/number-to-words#75]
Number: `2342535345365393436`:

Expected:
> два секстиллиона триста сорок два квадриллиона пятьсот тридцать пять триллионов триста сорок пять миллиардов триста шестьдесят пять миллионов триста девяноста три тысячи четыреста тридцать шесть

Actual:

> два секстиллиона триста сорок два квадриллиона пятьсот тридцать пять триллионов триста сорок пять миллиардов триста шестьдесят пять миллионов триста девяносто три тысячи четыреста восемь

---
Second number: `5342535345365393436`:

Expected:
> пять секстиллионов триста сорок два квадриллиона пятьсот тридцать пять триллионов триста сорок пять миллиардов триста шестьдесят пять миллионов триста девяноста три тысячи четыреста тридцать шесть

Actual:
> пять секстиллионов триста сорок два квадриллиона пятьсот тридцать пять триллионов триста сорок пять миллиардов триста шестьдесят пять миллионов триста девяносто три тысячи четыреста восемь

**Comment by kwn** [comment]
Hey, thanks for picking it up. I'm wondering if it's necessary to include sucha a large numbers in test cases. I'm wondering if we should put a limit on the exponent so we transform only numbers up to 10^15 or something like that.

**Comment by andrey-helldar** [comment]
In my practice, so large numbers did not occur in use at php.

**Comment by andrey-helldar** [comment]
In my opinion, tests need to cover all the code.
As for the limitation of the degree of the number, I think you can introduce a restriction. Thus, it will be easier to maintain the code. And if someone suddenly needs such large numbers, they will write about it.
