### ISSUE TITLE
Just add INR(Indian Rupee Currency) and when i just use number to words it doesn't shows anything for zero please fix, convert zero to words also.

### ISSUE THREAD

**Issue by coderboy-ss** [kwn/number-to-words#88]

**Comment by kwn** [comment]
Hi @coderboy-ss 

I don't understand what do you mean. Could you please either provide more details with examples, or alternatively fix it and create a pull request for that? Thanks.

**Comment by coderboy-ss** [comment]
1. I want to say that when you use NumberToWords functionality if you will pass 0 number in it, it doesn't return anything so we have to fix this by converting 0 number to word (zero) and return it.
2. This once is additional you have provided so many currencies but please also add INR (Indian Rupees) currency also.

**Comment by darshan922** [comment]
INR currency does not covert in words
i write this code 
             $numberToWords = new NumberToWords();
            $currencyTransformer = $numberToWords->getCurrencyTransformer('en');
            dd($currencyTransformer->toWords(5120,'en'));
getting this type error
Currency "EN" is not available for "NumberToWords\CurrencyTransformer\EnglishCurrencyTransformer" language

**Comment by ansh9d** [comment]
Presently they don't support INR.
Please Use 
        $input = (int)($input * 100); //converting float to integer value including paisa
        $numberToWords = new NumberToWords();
        $numberTransformer = $numberToWords->getCurrencyTransformer('en');
        $amtTransformed = $numberTransformer->toWords($input, 'USD');
        $amtTransformed = preg_replace("/dollars/", 'rupees', $amtTransformed);
        $amtTransformed = preg_replace("/dollar/", 'rupee', $amtTransformed);
        $amtTransformed = preg_replace("/cents/", 'paise', $amtTransformed);
        $amtTransformed = preg_replace("/cent/", 'paisa', $amtTransformed);
