### ISSUE TITLE
Invalid value for "const MINUS" in class Ua

### ISSUE THREAD

**Issue by igortyra** [kwn/number-to-words#91]
Hi, found little bug in
/src/Legacy/Numbers/Words/Locale/Ua.php
In Ukrainian, const MINUS must be "мінус".

**Comment by kwn** [comment]
Thank you for reporting it. Could you consider fixing it and opening a pull request?

**Comment by kwn** [comment]
Fixed in https://github.com/kwn/number-to-words/pull/111/files
