### ISSUE TITLE
Persian Support

### ISSUE THREAD

**Issue by mojtabaahn** [kwn/number-to-words#98]
Hi folks.

I Like the idea of supporting multiple languages in single library. So just tried ti implement Persian **based on English** classes.

It turned out its not possible to do such using current `GenericNumberTransformerBuilder` and it needs some modifications ( Adding another property like `$tripletSeparator`  and modifying some parts might solve this but seems overkill to me).

I spent last couple of hours and [made](https://github.com/mojtabaahn/php-persian-number-to-words) a number to words translator from scratch for Persian language. It has same test suite as english test and it is passing.

So was wondering if you have any interests in me creating a `NumberTransformer` wrapper for this language-specific implementation and make a pull request.

**Comment by kwn** [comment]
Hi @mojtabaahn 

Thank you for the comment and sorry for a very late reply. Currently Persian transformer is already implemented, but indeed it's not tested in any way. I used your test suite to validate my Persian transformer and indeed it seems that my one is broken (assuming the tests are correct).

My preference would be to avoid creating a wrapper for your package (I prefer not to have any external dependencies), but I'd really appreciate if you opened a pull request and add your code to my repository. If it's too difficult to follow the same pattern as in case of e.g. English language you can put the language specific classes to the `src/Language/Persian` directory and instantiate them appropriately in the `src/NumberTransformer/PersianNumberTransformer` class.
